apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wprs

spec:
  replicas: 1
  selector:
    matchLabels:
      dc: winterfell
      env: north
  template:
    metadata:
      name: mywp
      labels:
        dc: winterfell
        env: north
    spec:
      containers:
      - name: "wpcon"
        image: "wordpress:4.8-apache"